### ISSUE TITLE
04-05-reduce memory usage

### ISSUE THREAD

**Issue by ltetrel** [neurolibre/brainiak-tutorials#10]
@manojneuro

We updated our specifications here : https://github.com/neurolibre/submit#what-can-be-published-on-neurolibre

According to this, can you reduce the memory usage to less than 4GB for these notebooks ?

related to #5

**Comment by lunebellec** [comment]
@ltetrel this may require a lot of work. As this is a priority resource for the platform, is there any way to have a specific requirement for this notebook on the compute canada cloud?

**Comment by ltetrel** [comment]
As far as I know, it is not possible to have specific configuration for only one notebook.
The only thing that can be done is to give more resources to a specific user.

**Comment by manojneuro** [comment]
@pbellec we will down sample the dataset or use a mask on the data for this notebook and make it fit within the available memory.

**Comment by ltetrel** [comment]
Issue closed with PR #21 
Thanks to the contributors
