### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by manojneuro** [neurolibre/brainiak-tutorials#22]
@ltetrel I get a "403 : Forbidden" when I click on the binder badge.

**Comment by mathieuboudreau** [comment]
The binder link is wrong, it should point to this I think: https://binder.conp.cloud/v2/gh/neurolibre/brainiak-tutorials/master

**Comment by mathieuboudreau** [comment]
This line of the README file:

https://github.com/neurolibre/brainiak-tutorials/blame/master/README.md#L1

Should be this instead I think:

`[![Binder](https://binder.conp.cloud/badge_logo.svg)](https://binder.conp.cloud/v2/gh/neurolibre/brainiak-tutorials/master?filepath=tutorials)`
