### ISSUE TITLE
Binder not launching

### ISSUE THREAD

**Issue by manojneuro** [neurolibre/brainiak-tutorials#24]
I am getting the following error when trying to launch the neurolibre binder:
'''
This site can’t be reachedbinder.conp.cloud took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_TIMED_OUT
'''

**Comment by manojneuro** [comment]
@ltetrel any updates on this?

**Comment by ltetrel** [comment]
Our cloud supplier suffered from a partial outage, it seems like there are issues with the DNS resolving. I am in contact with our supplier to resolve this..

**Comment by ltetrel** [comment]
@manojneuro did you tried intensively to use the server last week (23th-25th) ? Or you just tried o few times ?

**Comment by manojneuro** [comment]
Just a few times.

**Comment by ltetrel** [comment]
and was it working at this time ?

**Comment by manojneuro** [comment]
It did work for a bit, the week before that. I was at SFN the following week, and didn't get a chance to use it regularly.

**Comment by manojneuro** [comment]
@ltetrel I am still getting errors launching the binder. Any workarounds?

**Comment by ltetrel** [comment]
Hi @manojneuro , I successfully managed to isolate the issue. It is quite technical and related to kubernetes internal load balancing and SSL certificate issuance.
@agahkarakuzu is working on the issue, we also have an external ressource that provide us some helps. Until it is not resolved, all the submissions are on hold.
You can look at the state of the server here : 
https://github.com/neurolibre/server-status

**Comment by ltetrel** [comment]
this is resolved
