### ISSUE TITLE
04-typo

### ISSUE THREAD

**Issue by ltetrel** [neurolibre/brainiak-tutorials#9]
@manojneuro Thanks to you and your team for the tutorials, they are really nice.
This is my first review mostly typos for notebook 04 

In the matlab stimulus file, the first row**s** codes for the stimulus category for each trial (1 = Faces, 2 = Scenes, 3 = Objects). The 3rd row contains the time (in seconds, relative to the start of the run) when the stimulus was presented for each trial.

In the matlab stimulus file, the first row codes for the stimulus category for each trial (1 = Faces, 2 = Scenes, 3 = Objects). => Are we loading a matlab file in python ?

The steps below are based on this example in scikit-learn. => the link is not working

**Comment by lunebellec** [comment]
@manojneuro any update?

**Comment by manojneuro** [comment]
This issue is addressed in PR #21. The scikit-learn example link has also been changed in the PR.

**Comment by ltetrel** [comment]
Resolved with issue #21 
Thanks to the contributors
